version: "3.9"

services:
  rdb:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testing
    ports:
      - "5432:5432"
    volumes:
      - rdb:/var/lib/postgresql/data
  go-barcode:
    image: cosmtrek/air
    working_dir: /project
    volumes:
      - ./:/project/
    ports:
      - "5000:8080"
    environment:
      - RDM_HOST=rdb
      - RDM_PORT=5432
      - RDM_USER=postgres
      - RDM_PASSWORD=example
      - RDM_DB=testing
      - TIME_ZONE=Asia/Bangkok
    command: air
    depends_on:
      - rdb

volumes:
  rdb:
    driver: local
