@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}

GET {{host}}/status HTTP/1.1
###

GET {{host}}/barcode HTTP/1.1
###

GET {{host}}/barcode/20 HTTP/1.1

###

POST {{host}}/barcode HTTP/1.1
content-type: application/json

{
    "courierCode": "DHL",
    "isCod": true,
    "startBarcode": "DCB00000001XTH",
    "batchSize": 10000
}
###

PATCH  {{host}}/barcode/3 HTTP/1.1
content-type: application/json

{
    "courierCode": "DHL",
    "isCod": true,
    "batchSize": 100000
}

###
DELETE  {{host}}/barcode/3 HTTP/1.1


###